
    /*
    JS
    --------------------------------------------------------------------------------------------  
    @site   			sho.com <common>
    @project            _
    @package            lang
    @file		        chronic.js
    @author				dpaul
    @modified			11.06.12
    @desc               mixin for Date, helps with conversions between 12 and 24 hour clocks
    -------------------------------------------------------------------------------------------- */  
    
    /**
     * class Date
     * The native javascript Date object is injected with instance methods from [[sho.lang.Chronic]]
    **/

    /**
     * mixin sho.lang.Chronic
     * Utility functions related to date and time. These are added to the [[Date]] primitive's prototype automatically, where they are available as instance methods.
    **/
    
    sho.lang.Chronic = {

        /**
         * Date#getMeridian() -> String 
         * Returns a string containing either 'PM' or 'AM', generated by inspecting the hour, if the meridian property has not been explicitly set.
        **/
        getMeridian:function()
        {
            if(this.meridian == null)
            {
                var h = this.getHours();
                this.meridian = h > 11 ? 'PM' : 'AM';
            }
            return this.meridian;
        },

        /**
         * Date#setMeridian() -> Null 
         * set the meridian flag by passing either a string ('AM' or 'PM') or a number (0 for AM, 1 for PM)
        **/
        setMeridian:function(m) // AM || PM || 0 || 1
        {
            if(typeof m == 'number') m = m == 1 ? 'PM' : 'AM';
            this.meridian = m;
        },

        /**
         * Date#to24Hour() -> Number 
         * convert the date to a 24 hour clock and return the hour.
        **/
        to24Hour:function()
        {
            var h = this.getHours();
            var m = this.getMeridian();
            if(m == 'PM' && h < 12) h += 12;
            if(m == 'AM' && h == 12) h = 0;
            return h;
        },

        /**
         * Date#to12Hour() -> Number 
         * convert the date to a 12 hour clock and return the hour.
        **/
        to12Hour:function()
        {
            var h = this.getHours();
            if( h > 11) h -= 12;
            if( h < 1 ) h = 12;
            return h;
        }

    };
    _.extend(Date.prototype, sho.lang.Chronic);

    /* No surrender, No delete! */

    